# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class NoiseProfile(BaseModel):
    # T2 dephasing contribution as a relative noise scale (policy: at most 10%).

    t2_dephasing_relative: typing.Optional[types.Checked[float, typing_extensions.Literal['t2_noise_under_10pct']]] = None
    # Thermal jitter contribution as a relative noise scale (policy: at most 10%).

    thermal_jitter_relative: typing.Optional[types.Checked[float, typing_extensions.Literal['thermal_noise_under_10pct']]] = None

class QuantumPulse(BaseModel):
    # Drive amplitude; physical range [0, 1]. Policy may require headroom below full scale.

    amplitude: typing.Optional[types.Checked[float, typing_extensions.Literal['amplitude_lt_1']]] = None
    # Drive frequency in Hz (SI).

    frequency_hz: typing.Optional[float] = None
    # Pulse duration in seconds (SI).

    duration_s: typing.Optional[float] = None
    gate_type: typing.Optional[types.GateType] = None
    # Optional digital-twin noise; omit for ideal (noiseless) execution.

    noise_profile: typing.Optional["NoiseProfile"] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
