# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class GateType(str, Enum):
    HADAMARD = "HADAMARD"
    X = "X"
    Y = "Y"
    Z = "Z"
    CNOT = "CNOT"
    PHASE = "PHASE"
    ROTATION = "ROTATION"
    CUSTOM = "CUSTOM"

# #########################################################################
# Generated classes (2)
# #########################################################################

class NoiseProfile(BaseModel):
    # T2 dephasing contribution as a relative noise scale (policy: at most 10%).

    t2_dephasing_relative: Checked[float, typing_extensions.Literal['t2_noise_under_10pct']]
    # Thermal jitter contribution as a relative noise scale (policy: at most 10%).

    thermal_jitter_relative: Checked[float, typing_extensions.Literal['thermal_noise_under_10pct']]

class QuantumPulse(BaseModel):
    # Drive amplitude; physical range [0, 1]. Policy may require headroom below full scale.

    amplitude: Checked[float, typing_extensions.Literal['amplitude_lt_1']]
    # Drive frequency in Hz (SI).

    frequency_hz: float
    # Pulse duration in seconds (SI).

    duration_s: float
    gate_type: GateType
    # Optional digital-twin noise; omit for ideal (noiseless) execution.

    noise_profile: typing.Optional["NoiseProfile"] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
